[package]
name = "thrust-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
tower-lsp = "0.20"
tower-service = "0.3.2"
tokio = { version = "1.37.0", features = ["full"] }

[dev-dependecies]
serde = { version="1.0", features=["derive"] }
serde_json = "1.0"

[lib]
path = "src/lsp.rs"
